app = "supagrafanaprom"

[env]
  SUPABASE_PROJECT_REF = "my_supabase_project_ref"
  SUPABASE_SERVICE_ROLE_KEY = "my_service_role_key"
  PASSWORD_PROTECTED = "false"
  GRAFANA_PASSWORD = "my_password"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
[mounts]
  source="data"
  destination="/data"