app = "supabase-grafana-metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="supabase_metrics_data"
  destination="/data"
