apiVersion: 1

datasources:
- name: prometheus
  datasourceUid: prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  jsonData:
  httpMethod: POST
  manageAlerts: true
  prometheusType: Prometheus
  prometheusVersion: 2.45.0
  cacheLevel: 'High'
  incrementalQuerying: true
  incrementalQueryOverlapWindow: 10m